# Generated by Django 6.0.5 on 2026-05-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Title", models.CharField(max_length=100)),
                ("Content", models.TextField()),
                ("Category", models.CharField(max_length=100)),
                ("Date_Published", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Username", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=100)),
                ("Password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Content", models.TextField()),
                ("Date_Posted", models.DateField()),
                (
                    "Post_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.user"
                    ),
                ),
            ],
        ),
    ]
