# Generated by Django 6.0.5 on 2026-05-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Post_ID",
            new_name="Post",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="User_ID",
            new_name="User",
        ),
    ]
